### ISSUE TITLE
phoneNumChanged attribut name could be changed?

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/NumberRecycling#19]
**Problem description**
Sorry to be picky but I'm not fan of using a abbreviation in the attribute name as we usually do not use abbreviation.
instead of `phoneNumChanged` why not `phoneNumberChanged` or `recycled` ?

`recycled` looks good because look similar to the `swapped` that we use for sim-swap or device-swap

**Possible evolution**

**Alternative solution**

**Additional context**

**Comment by yamamoto0104** [comment]
Dear @bigludo7. Thank you for your suggestion.
The attribute name is based on "phoneNumberChanged". But it was shortened to "phoneNumChanged" because the former name was very long.
The YAML file has been discussed over the past two months and merged, and the attribute name was agreed upon in the early stages. Therefore, I would like to proceed as is.
I understand that this does not breach any regulations.

**Comment by bigludo7** [comment]
Dear @yamamoto0104  Thanks you for taking time to answer.
This is fair. Happy that this point has been already discussed and agreed previously. I close this issue
