### ISSUE TITLE
Initial proposal for User Story of NumberRecycling API

### ISSUE THREAD

**Issue by yamamoto0104** [camaraproject/NumberRecycling#5]
**Problem description**

No User Story has yet been proposed
**Expected action**

A User Story proposal will be made.  Please discuss the proposal within this issue.

**Additional context**

**Comment by HuubAppelboom** [comment]
In the user story it says "whether there has been a change in the user associated with the phone number".  Probably you mean "the contract owner associated with the phone number".  Otherwise you would have to check who is actually using the subscription (maybe a  family member, or an employee of a company).

**Comment by HuubAppelboom** [comment]
Also, you probably want to check whether the phone number has been given up by a contract owner, and has returned to the pool of unused numbers.  The enterprise application developer can check with number recycle whether the phone number is still in use with the original contract owner.  There are two purposes for this : 1. to keep the end user administration of the application developer up to date, and to prevent unintended account access (as soon as the number is given to soeone else).

**Comment by yamamoto0104** [comment]
@eric-murray

**Comment by eric-murray** [comment]
@yamamoto0104 
Sure, but I would point @HuubAppelboom to the [Subscription Status API](https://github.com/camaraproject/APIBacklog/blob/main/documentation/API%20proposals/APIproposal_SubscriptionStatus.md).

We should avoid that two different APIs do the same thing. CAMARA APIs are intended to be atomic, and if an application developer's use case requires several different (possibly related) pieces of information, then the CAMARA approach is to make several separate API calls, rather than define "Swiss Army Knife" APIs that do everything.

**Comment by HuubAppelboom** [comment]
@eric-murray To me the Subscription Status API seems to be more targeting on whether the current subscrption is in good working order. It may for example be blocked temporarily because bills have not been paid, or in case of prepaid, their balance has run out.

As far as Number Recycle is concerned, I always understood that the use case is to prevent developers sending SMS-es to phone numbers which are no longer in use.  My comment above was that if you probably use end user in the definition, and in practice mean contract owner, you may be creating the wrong expectations with developers. I suggest to use "contract owner" in the definition.

**Comment by eric-murray** [comment]
Subscription Status is the API that stops you sending an SMS to a MSISDN no longer in use. Number Recycling stops you sending it to a MSISDN that is still in use, but has recently started being used by someone else.

I agree there is potentially a significant overlap in the scopes of these APIs, but they were submitted to and accepted by CAMARA as separate APIs.

**Comment by HuubAppelboom** [comment]
And then there is Tenure as well.

As far as I am concerned we should keep it as simple as possible.

Tenure: this shoud reflect the date & time when a phone number is issued to a contract owner. Usually this number will be coming form a pool of unused numbers.
Number Recycle: this should reflect the date & time when a phone number can no longer be used by a contract owner (because the contract has ended). Usually this means the number returns to the pool of unused numbers

This will probably be sufficient for most simple use cases. 

For cases where you also need to determine whether a user can use a specific communication service, I would use Subscription Status. There are many reasons why a particular communication service may not be available, and this may become quite a complex one.

**Comment by yamamoto0104** [comment]
> In the user story it says "whether there has been a change in the user associated with the phone number". Probably you mean "the contract owner associated with the phone number". Otherwise you would have to check who is actually using the subscription (maybe a family member, or an employee of a company).

You are right. We can update the term.

**Comment by yamamoto0104** [comment]
Hello @HuubAppelboom 
This API supports request/response operation and does not support subscription/notificaiton operation. This means the ASP cannot receive a notification as soon as the number is given to soeone else.

As state in the user story, when ASP sends SMS messages to an user (contract owner), it aims to prevent mis-delivery of SMS messages. Thus, the ASP uses this API before sending the SMS messages to check whether there has been a change in the user associated with the phone number after the specified date.

> Also, you probably want to check whether the phone number has been given up by a contract owner, and has returned to the pool of unused numbers. The enterprise application developer can check with number recycle whether the phone number is still in use with the original contract owner. There are two purposes for this : 1. to keep the end user administration of the application developer up to date, and to prevent unintended account access (as soon as the number is given to soeone else).

**Comment by HuubAppelboom** [comment]
@yamamoto0104 subscription / notification operation is indeed not necessary I believe. The customer can do these kinds of checks just before sending the SMS, or for example one time per month in a batch process to clean up the database.

**Comment by yamamoto0104** [comment]
Hello @eric-murray, @HuubAppelboom  
I'm OK to change "user" to "contract owner" and adding the sentence "to keep the end user administration of the application developer up to date".
I'm not sure whether other changes are needed at this moment. Because Tenure and Subscription Status APIs are also works in progress. PR #6 has been closed. What do you think?

**Comment by yamamoto0104** [comment]
Thank you for your clarification.
Based on the definition, we might want to apply "end user" to the User Story.

**Comment by eric-murray** [comment]
> Based on the definition, we might want to apply "end user" to the User Story.
The Number Recycling use case does not involve the physical device at all, and hence does not involve anyone who happens to be using that device (i.e. the "end user"). It involves the owner of the subscription, which CAMARA calls the "user". So "user" is the correct term.

**Comment by HuubAppelboom** [comment]
I was not aware that there is such a glossary.  Ok, in that case we can use "User".

**Comment by eric-murray** [comment]
> I was not aware that there is such a glossary. Ok, in that case we can use "User".

In fact, there are two glossaries! One in ICM and one in Commonalities. Someone needs to consolidate them, but that is a thankless task.

**Comment by yamamoto0104** [comment]
Thanks for your clarification. I'm OK to keep the "User" as is.

**Comment by Masa8106** [comment]
We confirmed at meeting today that this issue can be closed.
